#pragma config(Motor,  port3,           eFlyWheelPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           nFlyWheelPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           conveyorPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           nDrivingPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           eDrivingPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           eWiperPort,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//MOTORS
//ECU Fly wheel port 2
//NON fly wheel port 3
//conveyor port 4
//NON Driving wheel port 5
//ECU Driving wheel port 6
//ECU Wiper port 7
//NON Wiper port 8
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

// If there are issues with the program, comment this, as well as the motor off in the UsrCtrl, out.

bool blueAlliance = false;
bool redAlliance = false;      //Select Alliance.
int sp = 0;
int timingToCenter = 0;  // in ms. IMPORTANT!
									// FIND OUT TIMING TO CENTER
									// ON FOAM TILES. MAY DIFF.
task autonomous(){
  if (blueAlliance){
  	for (sp=0; sp < timingToCenter; sp++){
  		motor[eDrivingPort] = -127;
  		motor[nDrivingPort] = -127;
  		wait1Msec(1);
  		if (sp == timingToCenter-1){
  			// Do turn to face net. Differs between each alliance.
  		}
  	}
	}
  if (redAlliance){
  	for (sp=0; sp < timingToCenter; sp++){
  		motor[eDrivingPort] = -127;
  		motor[nDrivingPort] = -127;
  		wait1Msec(1);
  		if (sp == timingToCenter-1){
  			// Do turn to face net. Differs between each alliance.
  		}
  	}
	}
	// Now, spin up flywheel and turn on conveyor + wipers.
	motor[nFlyWheelPort] = 127;
	motor[eFlyWheelPort] = -127; // This may need to be reversed: -127,127
	wait10Msec(100); // Allow for motors to be fully spun up.
	motor[conveyorPort] = 36;
	motor[eWiperPort] = 60;
	// Will now launch balls until user ctrl.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
bool toggle = false;
int conveyWheels = 0;
task usercontrol()
{
	motor[eDrivingPort] = 0; // TURN ALL OFF. In case of auton mess up.
	motor[nDrivingPort] = 0;
	motor[conveyorPort] = 0;
	motor[eWiperPort] = 0;
	motor[nFlyWheelPort] = 0;
	motor[eFlyWheelPort] = 0;
	while (true)
	{
		//Resets the fly wheels to not moving when the button 5D is not pressed
		motor[eFlyWheelPort] = 0;
		motor[nFlyWheelPort] = 0;

		//Loop to detect if button 5D is ppressed
		while (vexRT[Btn5D]){
				//Sets the fly wheels to max powah
				motor[eFlyWheelPort] = 127;
				motor[nFlyWheelPort] = -127;
				//Loop enables the conveyor and wipers to turn on when the fly wheels are running
				while (vexRT[Btn6U]){
					motor[conveyorPort] = 36;
					motor[eWiperPort] = 60;
				}
				//Allows conveyor and wipers to turn off
				while (vexRT[Btn6D]){
					motor[conveyorPort] = 0;
					motor[eWiperPort] = 0;
				}
				//Monitors the joystick to enable driving while flywheels are in use
				motor[eDrivingPort] = -1 * vexRT[Ch3];
				motor[nDrivingPort] = -1 * vexRT[Ch2];
		}

		//outside loop to turn on conveyor and wipers when fly wheels are not in use
		while (vexRT[Btn6U]){
			motor[conveyorPort] = 36;
			motor[eWiperPort] = 60;

			/*
			FOR FUTURE USE!!!
			toggle = !toggle;
			if (!toggle){
				motor[conveyorPort] = 127;
			}else if(toggle){
				motor[conveyorPort] = 0;
			}
			*/
		}

		//Loope to turn off the conveyor and wipers when the fly wheels are not in use
		while (vexRT[Btn6D]){
			motor[conveyorPort] = 0;
			motor[eWiperPort] = 0;
		}

		//Outside loop to monitor driving controls when the fly wheels are not in use
		motor[eDrivingPort] = -1 * vexRT[Ch3];
		motor[nDrivingPort] = -1 * vexRT[Ch2];

	}
}
