#pragma config(Motor,  port3,           eFlyWheelPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port2,           nFlyWheelPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           conveyorPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           nDrivingPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port6,           eDrivingPort,         tmotorVex393, openLoop)
#pragma config(Motor,  port7,           eWiperPort,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//MOTORS
//ECU Fly wheel port 2
//NON fly wheel port 3
//conveyor port 4
//NON Driving wheel port 5
//ECU Driving wheel port 6   <-- may be port 9. change config to relfect this if true.
//ECU Wiper port 7
//NON Wiper port 8
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
																  //
// If there are issues with the program, comment this, as well as the motor off in the UsrCtrl, out.
                                //
bool blueAlliance = false;     //
bool redAlliance = false;     //Select Alliance.
int sp = 0;									 //
int timingToCenter = 0;  		// in ms. IMPORTANT!
													 // FIND OUT TIMING TO CENTER
													// ON FOAM TILES. MAY DIFF.
int autonTurnTime = 100; // Turn time to face the net. NEED TO DETERMINE CORRECT VAL. /100 for S value.
task autonomous(){			//
  if (blueAlliance){	 //
  	for (; sp < timingToCenter; sp++){
  		motor[eDrivingPort] = -127;
  		motor[nDrivingPort] = -127;
  		wait1Msec(1);
  		if (sp == timingToCenter-1){
  			// Do turn to face net. Differs between each alliance.
  			motor[eDrivingPort] = -127;
  			motor[nDrivingPort] = 127; // May need to be switched.
  			wait10Msec(autonTurnTime);
  			break;
  		}
  	}
	}
  if (redAlliance){
  	for (; sp < timingToCenter; sp++){
  		motor[eDrivingPort] = -127;
  		motor[nDrivingPort] = -127;
  		wait1Msec(1);
  		if (sp == timingToCenter-1){
  			// Do turn to face net. Differs between each alliance.
  			motor[eDrivingPort] = 127;
  			motor[nDrivingPort] = -127;  // May need to be switched.
  			wait10Msec(autonTurnTime);
  			break;
  		}
  	}
	}
	motor[eDrivingPort] = 0;
	motor[nDrivingPort] = 0;
	// Now, spin up flywheel and turn on conveyor + wipers.
	motor[nFlyWheelPort] = 127;
	motor[eFlyWheelPort] = -127; // This may need to be reversed: -127,127
	wait10Msec(100); // Allow for motors to be fully spun up.
	motor[conveyorPort] = 36;
	motor[eWiperPort] = 60;
	// Will now launch balls until user ctrl.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
bool toggle = false;
int rightCtrl = 0;
int leftCtrl = 0;
short conveyorCtrl;
short offConveyorCtrl;
short flywheelCtrl;
task usercontrol()
{
	motor[eDrivingPort] = 0; // TURN ALL OFF. In case of auton mess up.
	motor[nDrivingPort] = 0;
	motor[conveyorPort] = 0;
	motor[eWiperPort] = 0;
	motor[nFlyWheelPort] = 0;
	motor[eFlyWheelPort] = 0;
	while (true)
	{                            // Get Vals from Remote
		rightCtrl = vexRT[Ch2];   // ints, tank driving ctrl
		leftCtrl = vexRT[Ch3];

		conveyorCtrl = vexRT[Btn6U];  // bools
		offConveyorCtrl = vexRT[Btn6D]; // ISSUES WITH THIS. VexRT is type'word', i need bool.
		flywheelCtrl = vexRT[Btn5D];

		motor[eDrivingPort] = rightCtrl; // may need to be leftctrl
		motor[nDrivingPort] = leftCtrl; // same here

		if (conveyorCtrl == 1){
			motor[conveyorPort] = 36;
			motor[eWiperPort] = 60;
		} else if (offConveyorCtrl == 1){
			motor[conveyorPort] = 0;
			motor[eWiperPort] = 0;
		}

		if (flywheelCtrl == 1){
			motor[eFlyWheelPort] = 127;  // both of these may need to be reversed.
			motor[nFlyWheelPort] = -127;
		} else {
			motor[eFlyWheelPort] = 0;
			motor[nFlyWheelPort] = 0;
		}

	}
}
